export const creepNumbers: { [key: string]: number } = {
  mineSource: 1,
  workTerminal: 1,
  feedSpawn: 2,
  feedTower: 1,
  feedLink: 1,
  buildConstructionSite: 1,
  upgradeController: 1,
  lootResource: 1,
  scoutRoom: 1,
  claimRoom: 1,
  defendRoom: 1,
  reserveRoom: 1,
  transportResource: 1,
  terminalEngineer: 1,
  labEngineer: 1,
  factoryEngineer: 1,
  tankRoom: 0,
  dismantleEnemyBuildings: 1,
  harvestDeposit: 1
};
